# name: Continuous Deployment to Kubernetes

# on:
#   push:
#     branches:
#       - main  # Pipeline akan berjalan setiap kali ada push ke branch main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest  # Menggunakan runner Ubuntu

#     steps:
#       # Step 1: Checkout kode dari GitHub
#       - name: Checkout code
#         uses: actions/checkout@v2

#       # Step 2: Login ke Docker Hub
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       # Step 3: Build and Push Docker image
#       - name: Build and Push Docker image
#         run: |
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-todo-app .
#           docker push ${{ secrets.DOCKER_USERNAME }}/flask-todo-app

#       # Step 4: Set up Kubernetes
#       - name: Set up Kubernetes
#         uses: azure/setup-kubectl@v1
#         with:
#           kubeconfig: ${{ secrets.KUBE_CONFIG }}  # Pastikan kubeconfig sudah benar di Secrets

#       # Step 5: Deploy to Kubernetes
#       - name: Deploy to Kubernetes
#         run: |
#           kubectl apply -f deployment.yaml --validate=false  # Nonaktifkan validasi
#           kubectl apply -f service.yaml --validate=false     # Nonaktifkan validasi
