name: CI Pipeline

on:
  push:
    branches:
      - main

env:
  NAMESPACES: todo
  DEPLOYMENT_NAME: flask-todo-app
  CONTAINER_NAME: flask-todo-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover

      # Step 2: Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DEPLOYMENT_NAME}}:${{ github.sha }}


      - name: Deploy to cluster
        uses: nickgronow/kubectl@master
        with:
          config_data: ${{ secrets.K8S_CONFIG }}
          args: set image --record deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.CONTAINER_NAME }}=${{ secrets.DOCKER_USERNAME }}/flask-todo-app:${{ github.sha }} -n ${{ env.NAMESPACES }}
